In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
import h5py

In [2]:
chars = 'abcdefghijklmnopqrs'
coordinates = {k:v for v,k in enumerate(chars)}
chartonumbers = {k:v for k,v in enumerate(chars)}

def number_to_char(number):
    number_1, number_2 = divmod(number, 19)
    return chartonumbers[number_1] + chartonumbers[number_2]

def top_5_preds_with_chars(predictions):
    resulting_preds_numbers = [np.flip(np.argpartition(prediction, -5)[-5:]) for prediction in predictions]
    resulting_preds_chars = np.vectorize(number_to_char)(resulting_preds_numbers)
    return resulting_preds_chars

In [3]:
# model = load_model('./models/model_kyu_resnet50_withpp.h5')

# df = open('./CSVs/kyu_test_public.csv').read().splitlines()
# games_id = [i.split(',',2)[0] for i in df]

hdf5 = h5py.File('./hdf5/test.hdf5','r')
print(np.shape(hdf5))
x_testing = []
hdf5 = hdf5.get('Xs')
x_testing = np.array(hdf5[0])
print(x_testing[9])
x_testing = np.moveaxis(x_testing, 0, -1)
x=[]
x.append(x_testing)
x = np.array(x)
# for i in range()
print(np.shape(x))

# predictions = model.predict(x)
# prediction_chars = top_5_preds_with_chars(predictions)
# print(prediction_chars[0])

# with open('./public_submission_template.csv','a') as f:
#     for index in range(len(prediction_chars)):
#         answer_row = games_id[index] + ',' + ','.join(prediction_chars[index]) + '\n'
#         f.write(answer_row)

(2,)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

NameError: name 'model' is not defined

In [4]:
hdf5.close()

AttributeError: 'Dataset' object has no attribute 'close'

In [49]:
import h5py
import os
import numpy as np
if os.path.isfile('./hdf5/test.hdf5'):
    os.remove('./hdf5/test.hdf5')
hdf5 = h5py.File('./hdf5/test.hdf5', 'a')
hdf5.create_dataset('Xs', (0, 2, 2), maxshape=(None, 2, 2))
hdf5.create_dataset('Ys', (0, 1), maxshape=(None, 1))
x_dataset = hdf5['Xs']
y_dataset = hdf5['Ys']
x_batch = [] # Initialize data batch
y_batch = []
x_batch = [[[0,1],[1,2]]]
x_batch.append([[3,4],[5,6]])
print(len(x_batch), len(x_batch[0]))
print(x_batch)
x_dataset.resize(x_dataset.shape[0] + len(x_batch), axis = 0)
print(np.shape(x_dataset))
x_dataset[-len(x_batch):] = x_batch
print(x_dataset[1])

2 2
[[[0, 1], [1, 2]], [[3, 4], [5, 6]]]
(2, 2, 2)
[[3. 4.]
 [5. 6.]]


In [52]:
hdf5.close()